from PIL import Image, ImageChops, ImageOps, ImageDraw, ImageFont
import textwrap
import os

from xaipatimg.datagen.genimg import gen_img


def nhwc_to_nchw(x):
    if x.dim() == 4:
        x = x if x.shape[1] == 3 else x.permute(0, 3, 1, 2)
    elif x.dim() == 3:
        x = x if x.shape[0] == 3 else x.permute(2, 0, 1)
    return x

def nchw_to_nhwc(x):
    if x.dim() == 4:
        x = x if x.shape[3] == 3 else x.permute(0, 2, 3, 1)
    elif x.dim() == 3:
        x = x if x.shape[2] == 3 else x.permute(1, 2, 0)
    return x

def crop_white_border(im):
    bg = Image.new(im.mode, im.size, im.getpixel((0, 0)))
    diff = ImageChops.difference(im, bg)
    bbox = diff.getbbox()
    if bbox:
        return im.crop(bbox)

def add_margin(img, top, right, bottom, left, color):
    width, height = img.size
    new_width = width + right + left
    new_height = height + top + bottom
    result = Image.new(img.mode, (new_width, new_height), color)
    result.paste(img, (left, top))
    return result

def add_border(img):
    # Add a 1px border around the image
    return ImageOps.expand(img, border=1, fill="#f2f2f2")


def generate_llm_text_image(
        text,
        width=800,
        upper_height=150,
        lower_height=600,
        bg_color=(255, 255, 255),
        text_color=(0, 0, 0),
        font_size=40,
        margin=25,
        line_spacing=10,
        to_highlight=None,
        full_img_content=None,
        full_img_division=None):
    """
    Upper part: text image (same behavior as before).
    Lower part: image generated by gen_img.
    The two parts are concatenated vertically.
    """

    # --- TEXT IMAGE (upper part) ---
    text_img = Image.new("RGB", (width, upper_height), color=bg_color)
    draw = ImageDraw.Draw(text_img)

    def get_font(size):
        try:
            return ImageFont.truetype(
                "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf", size
            )
        except IOError:
            return ImageFont.load_default()

    def wrap_text_with_font(fnt):
        wrapped_lines = []
        for paragraph in text.split("\n"):
            words = paragraph.split()
            if not words:
                wrapped_lines.append("")
                continue
            current_line = ""
            for word in words:
                test_line = (current_line + " " + word).strip()
                if draw.textlength(test_line, font=fnt) <= (width - 2 * margin):
                    current_line = test_line
                else:
                    wrapped_lines.append(current_line)
                    current_line = word
            if current_line:
                wrapped_lines.append(current_line)
        return wrapped_lines

    current_size = font_size
    min_size = 10
    while current_size >= min_size:
        font = get_font(current_size)
        lines = wrap_text_with_font(font)
        line_height = font.getbbox("A")[3] - font.getbbox("A")[1]
        total_text_height = len(lines) * (line_height + line_spacing) - line_spacing

        fits = total_text_height <= (upper_height - 2 * margin) and all(
            draw.textlength(line, font=font) <= (width - 2 * margin)
            for line in lines
        )
        if fits:
            break
        current_size -= 2

    y = (upper_height - total_text_height) // 2

    for line in lines:
        x = margin
        for word in line.split(" "):
            draw.text((int(x), y), word, fill=text_color, font=font)
            x += draw.textlength(word + " ", font=font)
        y += line_height + line_spacing

    # --- GENERATED IMAGE (lower part) ---
    lower_img = gen_img(None, full_img_content, full_img_division, to_highlight=to_highlight,
                        draw_coordinates=True, return_image=True, dimension=(lower_height, lower_height))

    if lower_img.width != width:
        new_h = int(lower_img.height * (width / lower_img.width))
        lower_img = lower_img.resize((width, new_h))

    # --- VERTICAL CONCATENATION ---
    final_height = text_img.height + lower_img.height
    final_img = Image.new("RGB", (width, final_height), color=bg_color)

    final_img.paste(text_img, (0, 0))
    final_img.paste(lower_img, (0, text_img.height))

    return final_img
